server.port=8082
spring.application.name=quiosq
# Configuracao do PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/controle_mesa_quiosque}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
logging.level.com.zaxxer.hikari=INFO


springdoc.swagger-ui.defaultModelsExpandDepth=-1

spring.jackson.serialization.fail-on-empty-beans=false

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=loan-service
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

front-url = https://quiosque-node-site.onrender.com
#jwt-secret-key = &{4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P}

jwt.secret.key=${JWT_SECRET_KEY:4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P}

mercadopago.pago.base-url=https://api.mercadopago.com
mercadopago.client_id=${MP_CLIENT_ID:""}
mercadopago.client_secret=${MP_CLIENT_SECRET:""}
notification.base=https://2dd71508944e.ngrok-free.app
mercadopago.redirect_uri= ${notification.base}/api/token
mercadopago.redirect_pagamento= ${notification.base}/api/webhook/mercadopago
webhook.secret=${WEBHOOK_SECRET:""}


spring.jackson.time-zone=America/Sao_Paulo



