spring.application.name=quiosq
# Configuracao do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/controle-mesa-quiosque
spring.datasource.username=admin
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
logging.level.com.zaxxer.hikari=INFO


springdoc.swagger-ui.defaultModelsExpandDepth=-1

spring.jackson.serialization.fail-on-empty-beans=false

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=loan-service
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

front-url= http://localhost:4200
jwt-secret-key = 4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P
