server.port=8081
spring.application.name=quiosq
# Configuracao do PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

front-url = http://localhost:8080

jwt.secret.key=${JWT_SECRET_KEY:4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P}




