CREATE TABLE tb_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefone VARCHAR(255) NOT NULL,
    data_acesso TIMESTAMP,
    ultimo_acesso TIMESTAMP,
    role_id BIGINT NOT NULL,
    CONSTRAINT fk_cliente_role FOREIGN KEY (role_id) REFERENCES tb_roles(id)
);

CREATE TABLE tb_cliente_quiosque (
    cliente_id BIGINT NOT NULL,
    quiosque_id UUID NOT NULL,
    data_ultimo_acesso TIMESTAMP,
    PRIMARY KEY (cliente_id, quiosque_id),
    CONSTRAINT fk_cq_cliente FOREIGN KEY (cliente_id) REFERENCES tb_cliente(id) ON DELETE CASCADE,
    CONSTRAINT fk_cq_quiosque FOREIGN KEY (quiosque_id) REFERENCES tb_quiosque(id) ON DELETE CASCADE
);