CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefone VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    data_acesso TIMESTAMP,
    ultimo_acesso TIMESTAMP,
    role_id BIGINT NOT NULL,
    quiosque_id UUID NOT NULL,
    CONSTRAINT fk_cliente_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_cliente_quiosque FOREIGN KEY (quiosque_id) REFERENCES quiosque(id)
);